version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rails-example-mysql
    file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/rails-example-mysql
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 775
hooks:
  AfterInstall:
    - location: scripts/dependencies_install.sh
      runas: ubuntu
    - location: scripts/set_environment_variables.sh
      runas: ubuntu
    # run if have new migrate
    - location: scripts/restart_apache.sh
      runas: ubuntu